---
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: local_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 5s
      timeout: 3s
      retries: 5

  atlas:
    image: arigaio/atlas:latest
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/workspace
    working_dir: /workspace

volumes:
  pgdata:
